version: "3"
services:
  app:
    build: .
    container_name: react-native-app
    image: ardagon/react-native-urlget-app:latest
    restart: always
    ports:
      - 19000:19000
      - 19001:19001
      - 19002:19002
      - 19003:19003
      - 19004:19004
      - 19005:19005
      - 19006:19006
    volumes:
      - ./URLGet/App.js:/URLGet/App.js
    command: ["yarn", "web"]
